import { type Element } from './elements'

export type IngredientStats = Record<Element, [number, number]>

export interface Ingredient {
  id: string
  name: string
  description: string
  context: string
  src: string
  stats: IngredientStats
  rarity: number
}

export const ingredients: Ingredient[] = [
  // TIER 1 BASIC STAT BUFF - these are all berries
  {
    id: 'crimsonBerry',
    name: 'Crimson Berry',
    description: 'a fiery red berry that radiates warmth.',
    context: 'slight boost to fire properties',
    src: '/poke-ingredients/item_0169.png',
    stats: {
      fire: [8, 0.95],
      water: [0, 0.93],
      ground: [0, 0.95],
      electric: [0, 0.95],
      ice: [0, 0.88],
    },
    rarity: 1,
  },
  {
    id: 'sapphireBerry',
    name: 'Sapphire Berry',
    description: 'a translucent blue berry that glistens with morning dew.',
    context: 'slight boost to water properties',
    src: '/poke-ingredients/item_0165.png',
    stats: {
      fire: [0, 0.93],
      water: [9, 0.95],
      ground: [0, 0.95],
      electric: [0, 0.88],
      ice: [0, 0.98],
    },
    rarity: 1,
  },
  {
    id: 'thornrootBerry',
    name: 'Thornroot Berry',
    description: 'a rough, bark-like berry with earthy undertones.',
    context: 'slight boost to earth properties',
    src: '/poke-ingredients/item_0164.png',
    stats: {
      fire: [0, 0.95],
      water: [0, 0.96],
      ground: [8, 0.95],
      electric: [0, 0.88],
      ice: [0, 0.95],
    },
    rarity: 1,
  },
  {
    id: 'frostBerry',
    name: 'Frost Berry',
    description: 'a pale berry that feels cold to the touch.',
    context: 'slight boost to ice properties',
    src: '/poke-ingredients/item_0170.png',
    stats: {
      fire: [0, 0.85],
      water: [0, 0.98],
      ground: [0, 0.94],
      electric: [0, 0.95],
      ice: [8, 0.95],
    },
    rarity: 1,
  },
  {
    id: 'sparkBerry',
    name: 'Spark Berry',
    description: 'a golden berry that tingles with electric energy.',
    context: 'slight boost to lightning properties',
    src: '/poke-ingredients/item_0211.png',
    stats: {
      fire: [0, 0.93],
      water: [0, 0.85],
      ground: [0, 0.87],
      electric: [12, 0.9],
      ice: [0, 0.95],
    },
    rarity: 1,
  },
  // TIER 2 MEDIUM STAT BUFF - see context
  {
    // context: an eggplant shaped red vegetable with spikes.
    id: 'flameBulb',
    name: 'Flame Bulb',
    description: 'a spiky red bulb that radiates intense heat.',
    context: 'moderate boost to fire properties',
    src: '/poke-ingredients/item_0179.png',
    stats: {
      fire: [24, 0.95],
      water: [0, 0.93],
      ground: [0, 0.95],
      electric: [0, 0.95],
      ice: [0, 0.88],
    },
    rarity: 2,
  },
  {
    // context: a round, bumpy purple fruit
    id: 'tideFruit',
    name: 'Tide Fruit',
    description: 'a bumpy purple fruit that seems to contain rolling waves.',
    context: 'moderate boost to water properties',
    src: '/poke-ingredients/item_0160.png',
    stats: {
      fire: [0, 0.93],
      water: [24, 0.95],
      ground: [0, 0.95],
      electric: [0, 0.88],
      ice: [0, 0.98],
    },
    rarity: 2,
  },
  {
    // context: a weird, round brownish tuber
    id: 'stoneTuber',
    name: 'Stone Tuber',
    description: 'a dense, earthy root that anchors deep into soil.',
    context: 'moderate boost to earth properties',
    src: '/poke-ingredients/item_0163.png',
    stats: {
      fire: [0, 0.95],
      water: [0, 0.96],
      ground: [24, 0.95],
      electric: [0, 0.88],
      ice: [0, 0.95],
    },
    rarity: 2,
  },
  {
    // an oblong ice seed
    id: 'glacierSeed',
    name: 'Glacier Seed',
    description: 'an elongated seed encased in perpetual frost.',
    context: 'moderate boost to ice properties',
    src: '/poke-ingredients/item_0192.png',
    stats: {
      fire: [0, 0.85],
      water: [0, 0.98],
      ground: [0, 0.94],
      electric: [0, 0.95],
      ice: [24, 0.95],
    },
    rarity: 2,
  },
  {
    // a pineapple like yellow fruit
    id: 'thunderPine',
    name: 'Thunder Pine',
    description: 'a spiny yellow fruit that crackles with stored lightning.',
    context: 'moderate boost to lightning properties',
    src: '/poke-ingredients/item_0168.png',
    stats: {
      fire: [0, 0.93],
      water: [0, 0.85],
      ground: [0, 0.87],
      electric: [28, 0.9],
      ice: [0, 0.95],
    },
    rarity: 2,
  },
  // TIER 3 LARGE STAT BUFF - these are all gems
  {
    // context: star-shaped red gem
    id: 'stellarRuby',
    name: 'Stellar Ruby',
    description: 'a star-shaped crimson gem that burns with inner fire.',
    context: 'large boost to fire properties',
    src: '/poke-ingredients/item_0091.png',
    stats: {
      fire: [48, 0.95],
      water: [0, 0.93],
      ground: [0, 0.95],
      electric: [0, 0.95],
      ice: [0, 0.88],
    },
    rarity: 3,
  },
  {
    // context: a dark blue gem with bubbles inside
    id: 'abyssalSapphire',
    name: 'Abyssal Sapphire',
    description: 'a deep blue gem containing swirling currents of ancient seas.',
    context: 'large boost to water properties',
    src: '/poke-ingredients/item_0084.png',
    stats: {
      fire: [0, 0.93],
      water: [48, 0.95],
      ground: [0, 0.95],
      electric: [0, 0.88],
      ice: [0, 0.98],
    },
    rarity: 3,
  },
  {
    // context: a sun-shaped (disc with points along the side) brown gem
    id: 'solarCitrine',
    name: 'Solar Citrine',
    description: "a radiant disc-shaped gem that channels the earth's core energy.",
    context: 'large boost to earth properties',
    src: '/poke-ingredients/item_0080.png',
    stats: {
      fire: [0, 0.95],
      water: [0, 0.96],
      ground: [48, 0.95],
      electric: [0, 0.88],
      ice: [0, 0.95],
    },
    rarity: 3,
  },
  {
    // an icy gem with a snowflake
    id: 'eternalDiamond',
    name: 'Eternal Diamond',
    description: 'a crystalline gem bearing a perfect snowflake at its heart.',
    context: 'large boost to ice properties',
    src: '/poke-ingredients/item_0849.png',
    stats: {
      fire: [0, 0.85],
      water: [0, 0.98],
      ground: [0, 0.94],
      electric: [0, 0.95],
      ice: [48, 0.95],
    },
    rarity: 3,
  },
  {
    // a yellow prism
    id: 'stormPrism',
    name: 'Storm Prism',
    description: 'a brilliant yellow crystal that captures pure lightning essence.',
    context: 'large boost to lightning properties',
    src: '/poke-ingredients/item_0112.png',
    stats: {
      fire: [0, 0.93],
      water: [0, 0.85],
      ground: [0, 0.87],
      electric: [48, 0.9],
      ice: [0, 0.95],
    },
    rarity: 3,
  },
  // MISC WEIRD INGREDIENTS
  {
    // a bone
    id: 'bone',
    name: 'Bone',
    description: 'the bone of a skeleton',
    context: 'large boost to fire and earth, at the cost of water',
    src: '/poke-ingredients/item_0106.png',
    stats: {
      fire: [56, 0.93],
      water: [-6, 0.5],
      ground: [54, 0.93],
      electric: [0, 0.97],
      ice: [0, 0.97],
    },
    rarity: 4,
  },
  {
    id: 'mandrake_arm',
    name: 'Mandrake Arm',
    description: 'the arm of a mandrake',
    context: 'reduces earth potency, but improves all other elements',
    src: '/poke-ingredients/item_0035.png',
    stats: {
      fire: [16, 0.95],
      water: [16, 0.95],
      ground: [-3, 0.65],
      electric: [16, 0.97],
      ice: [18, 0.97],
    },
    rarity: 4,
  },
  {
    id: 'lemonleaf',
    name: 'Lemon Leaf',
    description: 'leaves from a lemon tree. very acidic!',
    context: 'large boost to water and lightning, at the cost of earth',
    src: '/poke-ingredients/item_0037.png',
    stats: {
      fire: [0, 0.97],
      water: [56, 0.96],
      ground: [-6, 0.5],
      electric: [50, 0.93],
      ice: [0, 0.97],
    },
    rarity: 4,
  },
  {
    id: 'iceflower',
    name: 'Ice Flower',
    description: 'an ice flower bloom. very cold and flower.',
    context: 'large boost to earth and ice, at the cost of fire',
    src: '/poke-ingredients/item_1239.png',
    stats: {
      fire: [-6, 0.5],
      water: [0, 0.97],
      ground: [56, 0.96],
      electric: [0, 0.97],
      ice: [50, 0.93],
    },
    rarity: 4,
  },
  {
    id: 'waterflower',
    name: 'Water Flower',
    description: 'a water flower bloom. very water and flower.',
    context: 'large boost to earth and water, at the cost of lightning',
    src: '/poke-ingredients/item_1237.png',
    stats: {
      fire: [0, 0.97],
      water: [56, 0.96],
      ground: [50, 0.93],
      electric: [-6, 0.5],
      ice: [0, 0.97],
    },
    rarity: 4,
  },
  {
    id: 'oddstatue',
    name: 'Odd Statue',
    description: 'an ominous rock statue.',
    context: 'reduces lightning potency, but improves all other elements',
    src: '/poke-ingredients/item_0111.png',
    stats: {
      fire: [16, 0.95],
      water: [16, 0.95],
      ground: [16, 0.97],
      electric: [-3, 0.65],
      ice: [18, 0.97],
    },
    rarity: 4,
  },
  {
    id: 'electricbeak',
    name: 'Electric Beak',
    description: 'the beak of a lightning bird.',
    context: 'large boost to fire and lightning, at the cost of ice',
    src: '/poke-ingredients/item_0244.png',
    stats: {
      fire: [56, 0.96],
      water: [0, 0.97],
      ground: [0, 0.97],
      electric: [50, 0.93],
      ice: [-6, 0.5],
    },
    rarity: 4,
  },
  {
    id: 'iceleaf',
    name: 'IceLeaf',
    description: 'a frosty leaf.',
    context: 'large boost to ice and water, at the cost of fire',
    src: '/poke-ingredients/item_0219.png',
    stats: {
      fire: [-6, 0.5],
      water: [50, 0.93],
      ground: [0, 0.97],
      electric: [0, 0.97],
      ice: [56, 0.96],
    },
    rarity: 4,
  },
  {
    id: 'terrabanana',
    name: 'Terra Banana',
    description: 'an earthly banana.',
    context: 'large boost to earth and lightning, at the cost of water',
    src: '/poke-ingredients/item_0166.png',
    stats: {
      fire: [0, 0.97],
      water: [-6, 0.5],
      ground: [50, 0.93],
      electric: [56, 0.96],
      ice: [0, 0.97],
    },
    rarity: 4,
  },
  {
    id: 'vodka',
    name: 'Vodka',
    description: 'an alcoholic beverage.',
    context: 'large boost to fire and water, at the cost of earth',
    src: '/poke-ingredients/item_0030.png',
    stats: {
      fire: [50, 0.93],
      water: [56, 0.96],
      ground: [-6, 0.5],
      electric: [0, 0.97],
      ice: [0, 0.97],
    },
    rarity: 4,
  },
  // UNIVERSAL ELEMENTS
  {
    id: 'rainbowfruit',
    name: 'Rainbow Fruit',
    description: 'a fruit that sparkles with all colors.',
    context: 'slight boost to all elements',
    src: '/poke-ingredients/item_0207.png',
    stats: {
      fire: [8, 0.97],
      water: [8, 0.97],
      ground: [8, 0.97],
      electric: [8, 0.97],
      ice: [8, 0.97],
    },
    rarity: 5,
  },
  {
    id: 'pearl',
    name: 'Pearl',
    description: 'a shimmering pearl. devoid of impurities.',
    context: 'moderate boost to all elements',
    src: '/poke-ingredients/item_0088.png',
    stats: {
      fire: [20, 1],
      water: [20, 1],
      ground: [20, 1],
      electric: [20, 1],
      ice: [20, 1],
    },
    rarity: 5,
  },
  {
    id: 'largepearl',
    name: 'Large Pearl',
    description: 'a radiant pearl. flawless.',
    context: 'large boost to all elements',
    src: '/poke-ingredients/item_0089.png',
    stats: {
      fire: [40, 1],
      water: [40, 1],
      ground: [40, 1],
      electric: [40, 1],
      ice: [40, 1],
    },
    rarity: 5,
  },
  {
    id: 'baguettesandwich',
    name: 'Baguette Sandwich',
    description: 'a baguette sandwich. strangely equilibrious.',
    context: 'all elements tend towards 50% potency.',
    src: '/poke-ingredients/item_1830.png',
    stats: {
      fire: [50, 0.5],
      water: [50, 0.5],
      ground: [50, 0.5],
      electric: [50, 0.5],
      ice: [50, 0.5],
    },
    rarity: 5,
  },
  {
    id: 'regressioncube',
    name: 'Cube of Regression',
    description: 'a cube that emanates void energy.',
    context: 'slight decrease to all elements.',
    src: '/poke-ingredients/item_1886.png',
    stats: {
      fire: [-8, 1],
      water: [-8, 1],
      ground: [-8, 1],
      electric: [-8, 1],
      ice: [-8, 1],
    },
    rarity: 5,
  },
  // FLOWERS
  {
    id: 'firebranch',
    name: 'Fiery Branch',
    description: 'a flaming branch. it turns all into flames.',
    context: 'fire 100%. all other elements 0.',
    src: '/poke-ingredients/item_1908.png',
    stats: {
      fire: [100, 1],
      water: [0, 0],
      ground: [0, 0],
      electric: [0, 0],
      ice: [0, 0],
    },
    rarity: 5,
  },
  {
    id: 'icebranch',
    name: 'Icy Branch',
    description: 'an icy branch. it turns all into frost.',
    context: 'ice 100%. all other elements 0.',
    src: '/poke-ingredients/item_1905.png',
    stats: {
      fire: [0, 0],
      water: [0, 0],
      ground: [0, 0],
      electric: [0, 0],
      ice: [100, 1],
    },
    rarity: 5,
  },
  {
    id: 'electricbranch',
    name: 'Electrified Branch',
    description: 'an electrified branch. it turns all into lightning.',
    context: 'lightning 100%. all other elements 0.',
    src: '/poke-ingredients/item_1906.png',
    stats: {
      fire: [0, 0],
      water: [0, 0],
      ground: [0, 0],
      electric: [100, 1],
      ice: [0, 0],
    },
    rarity: 5,
  },
]

// export const old_ingredients: Ingredient[] = [
//   {
//     id: 'crimsonBerry',
//     name: 'Crimson Berry',
//     description: 'A fiery red berry that radiates warmth.',
//     context: 'Increases fire potency but dampens ice properties.',
//     src: '/poke-ingredients/item_0158.png',
//     stats: {
//       fire: [15, 0.7],
//       water: [0, 0.6],
//       ground: [0, 0.7],
//       electric: [0, 0.8],
//       ice: [0, 0.4],
//     },
//   },
//   {
//     id: 'azureBloom',
//     name: 'Azure Bloom',
//     description: 'A delicate blue flower that seems to shimmer with moisture.',
//     context: 'Enhances water magic significantly.',
//     src: '/poke-ingredients/item_0159.png',
//     stats: {
//       fire: [0, 0.7],
//       water: [18, 0.7],
//       ground: [0, 0.8],
//       electric: [0, 0.5],
//       ice: [1, 0.9],
//     },
//   },
//   {
//     id: 'earthRoot',
//     name: 'Earth Root',
//     description: 'A thick, gnarled root that pulses with earthen energy.',
//     context: 'Stabilizes ground-based effects.',
//     src: '/poke-ingredients/item_0160.png',
//     stats: {
//       fire: [0, 0.8],
//       water: [0, 0.8],
//       ground: [15, 0.8],
//       electric: [0, 0.4],
//       ice: [0, 0.8],
//     },
//   },
//   {
//     id: 'thunderFruit',
//     name: 'Thunder Fruit',
//     description: 'A spiky yellow fruit that crackles with static electricity.',
//     context: 'Amplifies electrical properties.',
//     src: '/poke-ingredients/item_0161.png',
//     stats: {
//       fire: [2, 0.9],
//       water: [0, 0.6],
//       ground: [0, 0.8],
//       electric: [16, 0.9],
//       ice: [1, 0.9],
//     },
//   },
//   {
//     id: 'frostPetal',
//     name: 'Frost Petal',
//     description: 'A crystalline white petal that never melts.',
//     context: 'Greatly enhances ice magic at the cost of fire.',
//     src: '/poke-ingredients/item_0162.png',
//     stats: {
//       fire: [0, 0.3],
//       water: [5, 0.9],
//       ground: [0, 0.8],
//       electric: [3, 0.9],
//       ice: [19, 0.8],
//     },
//   },
//   {
//     id: 'emberCap',
//     name: 'Ember Cap',
//     description: 'A small mushroom with an orange glow.',
//     context: 'Provides steady fire enhancement with minor side effects.',
//     src: '/poke-ingredients/item_0163.png',
//     stats: { fire: [8, 0.8], water: [0, 0.9], ground: [4, 0.9], electric: [2, 0.9], ice: [0, 0.7] },
//   },
//   {
//     id: 'stormSeed',
//     name: 'Storm Seed',
//     description: 'A dark seed that hums with electric potential.',
//     context: 'Balances electric and water energies.',
//     src: '/poke-ingredients/item_0164.png',
//     stats: { fire: [0, 0.9], water: [7, 0.9], ground: [1, 0.9], electric: [9, 0.9], ice: [2, 0.9] },
//   },
//   {
//     id: 'crystalBerry',
//     name: 'Crystal Berry',
//     description: 'A translucent berry with ice formations.',
//     context: 'Creates powerful ice effects while reducing fire.',
//     src: '/poke-ingredients/item_0165.png',
//     stats: {
//       fire: [0, 0.4],
//       water: [3, 0.9],
//       ground: [0, 0.9],
//       electric: [1, 0.9],
//       ice: [14, 0.8],
//     },
//   },
//   {
//     id: 'vineHeart',
//     name: 'Vine Heart',
//     description: 'The core of an ancient vine, rich with earth essence.',
//     context: 'Provides strong ground magic boost.',
//     src: '/poke-ingredients/item_0166.png',
//     stats: {
//       fire: [0, 0.8],
//       water: [6, 0.9],
//       ground: [17, 0.8],
//       electric: [0, 0.8],
//       ice: [0, 0.8],
//     },
//   },
//   {
//     id: 'voidShard',
//     name: 'Void Shard',
//     description: 'A mysterious black crystal that absorbs all light.',
//     context: 'Resets all element values to zero, providing a clean slate.',
//     src: '/poke-ingredients/item_0167.png',
//     stats: { fire: [0, 0.0], water: [0, 0.0], ground: [0, 0.0], electric: [0, 0.0], ice: [0, 0.0] },
//   },
//   {
//     id: 'harmonicCrystal',
//     name: 'Harmonic Crystal',
//     description: 'A prismatic gem that hums with balanced energy.',
//     context: 'Provides modest increases to all elements equally.',
//     src: '/poke-ingredients/item_0168.png',
//     stats: { fire: [5, 0.9], water: [5, 0.9], ground: [5, 0.9], electric: [5, 0.9], ice: [5, 0.9] },
//   },
//   {
//     id: 'moltenCore',
//     name: 'Molten Core',
//     description: 'A glowing sphere of pure flame essence.',
//     context: 'Extreme fire enhancement but severely weakens all other elements.',
//     src: '/poke-ingredients/item_0169.png',
//     stats: {
//       fire: [25, 0.9],
//       water: [0, 0.2],
//       ground: [0, 0.3],
//       electric: [0, 0.4],
//       ice: [0, 0.1],
//     },
//   },
//   {
//     id: 'steadyStone',
//     name: 'Steady Stone',
//     description: 'A smooth, warm rock that pulses gently.',
//     context: 'Provides consistent moderate boosts with minimal side effects.',
//     src: '/poke-ingredients/item_0170.png',
//     stats: { fire: [6, 0.9], water: [6, 0.9], ground: [8, 0.9], electric: [6, 0.9], ice: [6, 0.9] },
//   },
//   {
//     id: 'chaosSpore',
//     name: 'Chaos Spore',
//     description: 'A swirling, multicolored fungal spore.',
//     context: 'Unpredictable effects that can dramatically shift element balance.',
//     src: '/poke-ingredients/item_0171.png',
//     stats: {
//       fire: [12, 0.5],
//       water: [8, 0.6],
//       ground: [15, 0.4],
//       electric: [20, 0.3],
//       ice: [10, 0.7],
//     },
//   },
//   {
//     id: 'purifyingMist',
//     name: 'Purifying Mist',
//     description: 'A shimmering vapor that cleanses impurities.',
//     context: 'Amplifies all positive effects while maintaining stability.',
//     src: '/poke-ingredients/item_0172.png',
//     stats: { fire: [3, 1.0], water: [3, 1.0], ground: [3, 1.0], electric: [3, 1.0], ice: [3, 1.0] },
//   },
//   {
//     id: 'primalEssence',
//     name: 'Primal Essence',
//     description: 'Ancient energy contained in a swirling orb.',
//     context: 'Massive power boost to dominant element while suppressing others.',
//     src: '/poke-ingredients/item_0173.png',
//     stats: {
//       fire: [30, 0.8],
//       water: [30, 0.8],
//       ground: [30, 0.8],
//       electric: [30, 0.8],
//       ice: [30, 0.8],
//     },
//   },
//   {
//     id: 'neutralAgent',
//     name: 'Neutral Agent',
//     description: 'A clear, odorless liquid that seems to do nothing.',
//     context: 'Gradually reduces all element intensities toward neutral.',
//     src: '/poke-ingredients/item_0174.png',
//     stats: { fire: [0, 0.8], water: [0, 0.8], ground: [0, 0.8], electric: [0, 0.8], ice: [0, 0.8] },
//   },
//   {
//     id: 'wildcardHerb',
//     name: 'Wildcard Herb',
//     description: 'A strange plant that changes color constantly.',
//     context: 'Randomly enhances one element while weakening its opposite.',
//     src: '/poke-ingredients/item_0175.png',
//     stats: {
//       fire: [15, 0.6],
//       water: [15, 0.6],
//       ground: [10, 0.7],
//       electric: [12, 0.6],
//       ice: [15, 0.6],
//     },
//   },
//   {
//     id: 'amplifierDust',
//     name: 'Amplifier Dust',
//     description: 'Fine golden powder that sparkles with potential.',
//     context: 'Doubles the effectiveness of other ingredients without adding elements.',
//     src: '/poke-ingredients/item_0176.png',
//     stats: { fire: [0, 1.2], water: [0, 1.2], ground: [0, 1.2], electric: [0, 1.2], ice: [0, 1.2] },
//   },
// ]
